server:
  port: 8087
  servlet:
    context-path: '/ead-authuser/'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
    password: banco123
  jpa:
    hibernate:
      ddlAuto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdcb:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: ALWAYS

ead:
  api:
    url:
      course: 'http://localhost:8082/ead-course'

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO